simulated_motors:
  - "/hrim_actuation_servomotor_000000000001/trajectory_axis2"
  - "/hrim_actuation_servomotor_000000000001/trajectory_axis1"
  - "/hrim_actuation_servomotor_000000000002/trajectory_axis1"

real_motors:
  - "/hrim_actuation_servomotor_70B3D521A042/trajectory_axis2"
  - "/hrim_actuation_servomotor_70B3D521A042/trajectory_axis1"
  - "/hrim_actuation_servomotor_70B3D521A08A/trajectory_axis1"
